services:
  node:
    image: "node:20"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
